import React from 'react';
import { Card } from './common.jsx';
import { formatDate } from '../lib/format.js';

function AuditTable({ title, rows }) {
  return <div className="audit-table-wrap">
    <h3>{title}</h3>
    <table className="audit-table"><tbody>{(rows || []).slice(0, 10).map((row) => <tr key={row.id}>
      <td>{formatDate(row.created_at)}</td><td>{row.symbol || row.regime_name || row.action || '—'}</td>
      <td>{row.signal || row.status || row.side || row.multiplier || row.source || '—'}</td>
      <td>{row.qty || row.price || row.reason || row.alpaca_order_id || '—'}</td>
    </tr>)}</tbody></table>
    {(!rows || rows.length === 0) && <p className="hint">No audit rows yet.</p>}
  </div>;
}

export default function AuditTrail({ data }) {
  return <Card title="Bot Audit Trail">
    <p className="hint">Bot audit rows are generated by this application. Broker account state below comes directly from Alpaca and may include historical/manual activity outside the bot.</p>
    <div className="audit-summary">{Object.entries(data.auditSummary?.summary || {}).map(([key, value]) => <div key={key}><span>{key.replaceAll('_', ' ')}</span><strong>{value ?? '—'}</strong></div>)}</div>
    <div className="audit-grid">
      <AuditTable title="Bot Signals" rows={data.auditSignals?.rows} /><AuditTable title="Bot Decisions" rows={data.auditDecisions?.rows} />
      <AuditTable title="Bot Orders" rows={data.auditOrders?.rows} /><AuditTable title="Bot Fills" rows={data.auditFills?.rows} />
      <AuditTable title="Regime States" rows={data.auditRegimes?.rows} />
    </div>
  </Card>;
}
